# encoding: UTF-8
module Util
  def self.my_log(text, file = "", line = "")
    text.to_s.chomp.gsub!(/%/, "%%")
    Rails.logger.debug(sprintf("\033[32m#{file}#{line}\033[0m\033[1m\033[33m#{text}\033[0m"))
  end

  def self.text_cleaner(t)
    # http://graphemica.com/ᵼ
    t = t.to_s
    t = t.gsub(/[ÁÀĂÂẮẰẴẲẤẦẪẨǍÅǺÄǞÃȦǠĄĀẢȀȂẠẶẬḀȺ]/,'A')
    t = t.gsub(/[áàăâắằẵẳấầẫẩǎåǻäǟãȧǡąāảȁȃạặậḁⱥᶏᶐ]/,'a')
    t = t.gsub(/[ÍÌĬÎǏÏḮĨĮĪỈȈȊỊḬƗİ]/,'I')
    t = t.gsub(/[íìĭîǐïḯĩįīỉȉȋịḭɨᶖᵼ]/,'i')
    t = t.gsub(/[ÚÙŬÛǓŮÜǗǛǙǕŰŨṸŲŪṺỦȔȖƯỨỪỮỬỰỤṲṶṴɄ]/,'U')
    t = t.gsub(/[úùŭûǔůüǘǜǚǖűũṹųūṻủȕȗưứừữửựụṳṷṵʉᵾᶙʮʯɰᵿ]/,'u')
    t = t.gsub(/[ÉÈĔÊẾỀỄỂĚËẼĖȨḜĘĒḖḔẺȄȆẸỆḘḚɆ]/,'E')
    t = t.gsub(/[éèĕêếềễểěëẽėȩḝęēḗḕẻȅȇẹệḙḛɇᶒⱸᶕᶓɚᶔɝ]/,'e')
    t = t.gsub(/[ÓÒŎÔỐỒỖỔǑÖȪŐÕṌṎȬȮȰØǾǪǬŌṒṐỎȌȎƠỚỜỠỞỢỌỘꝊꝌ]/,'O')
    t = t.gsub(/[óòŏôốồỗổǒöȫőõṍṏȭȯȱøǿǫǭōṓṑỏȍȏơớờỡởợọộꝋꝍᴓᶗⱺ]/,'o')
    t = t.gsub(/[ḂḄḆɃƁ]/,'B')
    t = t.gsub(/[ḃḅḇƀᵬᶀɓƂƃ]/,'b')
    t = t.gsub(/[ĆĈČĊÇḈȻƇꜾ]/,'C')
    t = t.gsub(/[ćĉčċçḉȼƈꜿɕ]/,'c')
    t = t.gsub(/[ĎḊḐḌḒḎĐƉƊƋ]/,'D')
    t = t.gsub(/[ďḋḑḍḓḏđɖɗƌᵭᶁᶑȡ]/,'d')
    t = t.gsub(/[ḞƑ]/,'F')
    t = t.gsub(/[ḟƒᵮᶂ]/,'f')
    t = t.gsub(/[ǴĞĜǦĠĢḠƓǤʛ]/,'G')
    t = t.gsub(/[ǵğĝǧġģḡɠꞠꞡǥᶃ]/,'g')
    t = t.gsub(/[ĤȞḦḢḨḤḪH̱ĦⱧ]/,'H')
    t = t.gsub(/[ĥȟḧḣḩḥḫẖħⱨɦɧ]/,'h')
    t = t.gsub(/[ĴJ̌]/,'J')
    t = t.gsub(/[ĵǰɈɉʝɟʄ]/,'j')
    t = t.gsub(/[ḰǨĶꞢḲḴƘⱩ]/,'K')
    t = t.gsub(/[ḱǩķꞣḳḵƙⱪᶄꝀꝁꝂꝃꝄꝅ]/,'k')
    t = t.gsub(/[ĹĽĻḶḸḼḺŁꝈȽⱠⱢɬ]/,'L')
    t = t.gsub(/[ĺľļḷḹḽḻłꝉƚⱡɫᶅɭꞎȴƛ]/,'l')
    t = t.gsub(/[ḾṀṂⱮ]/,'M')
    t = t.gsub(/[ḿṁṃɱᵯᶆ]/,'m')
    t = t.gsub(/[ŃǸŇÑṄŅꞤṆṊṈᵰƝɲȠƞꞐꞑᶇɳȵ]/,'N')
    t = t.gsub(/[ŃńǸǹŇňÑñṄṅŅņꞤꞥṆṇṊṋṈṉᵰƝɲȠƞꞐꞑᶇɳȵ]/,'n')
    t = t.gsub(/[ṔṕṖṗⱣᵽꝐꝑᵱᶈƤƥꝒꝓꝔꝕꝖꝗꝘꝙʠ]/,'P')
    t = t.gsub(/[Ɋɋ]/,'Q')
    t = t.gsub(/[ŔŕŘřṘṙŖŗȐȑȒȓṚṛṜṝṞṟɌɍᵲɺᶉɻⱹɼⱤɽɾᵳɿ]/,'R')
    t = t.gsub(/[ŚśṤṥŜŝŠšṦṧṠṡŞşꞨꞩṢṣṨṩȘșẛᵴᶊʂⱾȿẜẝᶋᶘʆ]/,'S')
    t = t.gsub(/[ẞ]/,'SS')
    t = t.gsub(/[ß]/,'ss')
    t = t.gsub(/[ŤťT̈ẗṪṫŢţṬṭȚțṰṱṮṯƾŦŧȾⱦᵵƫƬƭƮʈȶ]/,'T')
    t = t.gsub(/[ṼṽṾṿꝞꝟᶌƲʋⱱⱴ]/,'V')
    t = t.gsub(/[ẂẃẀẁŴŵW̊ẘẄẅẆẇẈẉⱲⱳ]/,'W')
    t = t.gsub(/[ẌẍẊẋᶍ]/,'X')
    t = t.gsub(/[ÝýỲỳŶŷY̊ẙŸÿỸỹẎẏȲȳỶỷỴỵɎɏƳƴỾỿ]/,'Y')
    t = t.gsub(/[ŹźẐẑŽžŻżẒẓẔẕƵƶᵶᶎȤȥʐʑⱿɀⱫⱬǮǯᶚƺʓꝤꝥꝦꝧƻꜮꜯʡʢ]/,'Z')
    t = t.gsub(/[Ꜳ]/,'AA')
    t = t.gsub(/[ÆǼǢᴁ]/,'AE')
    t = t.gsub(/[æǽǣᴂ]/,'ae')
    t = t.gsub(/[Ꜵ]/,'AO')
    t = t.gsub(/[ꜵ]/,'ao')
    t = t.gsub(/[Ꜷ]/,'AU')
    t = t.gsub(/[ꜷ]/,'au')
    t = t.gsub(/[ꜸꜺ]/,'AV')
    t = t.gsub(/[ꜹꜻ]/,'av')
    t = t.gsub(/[Ꜽ]/,'AY')
    t = t.gsub(/[ꜽ]/,'ay')
    t = t.gsub(/[ȸ]/,'db')
    t = t.gsub(/[ǱǲǳʣǄǅǆʥʤ]/,'Dz')
    t = t.gsub(/[ﬀ]/,'ff')
    t = t.gsub(/[ﬁ]/,'fi')
    t = t.gsub(/[ﬂ]/,'fl')
    t = t.gsub(/[ʩ]/,'feng')
    t = t.gsub(/[Ĳ]/,'IJ')
    t = t.gsub(/[ĳ]/,'ij')
    t = t.gsub(/[Ǉ]/,'LJ')
    t = t.gsub(/[ǈ]/,'Lj')
    t = t.gsub(/[ǉ]/,'lj')
    t = t.gsub(/[Ỻỻ]/,'LL')
    t = t.gsub(/[ʪ]/,'ls')
    t = t.gsub(/[ʫ]/,'lz')
    t = t.gsub(/[Ǌǋǌ]/,'NJ')
    t = t.gsub(/[Ǌǋǌ]/,'Nj')
    t = t.gsub(/[Ǌǋǌ]/,'nj')
    t = t.gsub(/[Œ]/,'OE')
    t = t.gsub(/[œɶ]/,'oe')
    t = t.gsub(/[Ꝏ]/,'OO')
    t = t.gsub(/[ꝏ]/,'oo')
    t = t.gsub(/[ᴔ]/,'eo')
    t = t.gsub(/[ȹ]/,'qp')
    t = t.gsub(/[ﬆ]/,'st')
    t = t.gsub(/[ﬅ]/,'ft')
    t = t.gsub(/[ʨ]/,'tc')
    t = t.gsub(/[ᵺ]/,'th')
    t = t.gsub(/[ʦ]/,'ts')
    t = t.gsub(/[ʧ]/,'ts')
    t = t.gsub(/[Ꜩꜩ]/,'tz')
    t = t.gsub(/[ᵫ]/,'ue')
    t = t.gsub(/[Ꝡꝡ]/,'vy')
    t = t.gsub(/[']/,' ')      # Es. Sant'Agata Feltria
    t = t.gsub(/[-_\/]/,' ')   # Es. Emilia-Romagna
    t = t.gsub(/\s{2,}/,' ')   # Remove double spaces
    return t
  end

  def self.from_country_to_two_letter_code(country)
    # This take the country name as returned by MAP API and convert it to two letters code.
    unless @mapping
      @mapping = {
	"afghanistan" => "af",
	"aland islands" => "ax",
	"albania" => "al",
	"algeria" => "dz",
	"american samoa" => "as",
	"andorra" => "ad",
	"angola" => "ao",
	"anguilla" => "ai",
	"antarctica" => "aq",
	"antigua and barbuda" => "ag",
	"argentina" => "ar",
	"armenia" => "am",
	"aruba" => "aw",
	"australia" => "au",
	"austria" => "at",
	"azerbaijan" => "az",
	"bahamas" => "bs",
	"bahrain" => "bh",
	"bangladesh" => "bd",
	"barbados" => "bb",
	"belarus" => "by",
	"belgium" => "be",
	"belize" => "bz",
	"benin" => "bj",
	"bermuda" => "bm",
	"bhutan" => "bt",
	"bolivia" => "bo",
	"bonaire, saint eustatius and saba" => "bq",
	"bosnia and herzegovina" => "ba",
	"botswana" => "bw",
	"bouvet island" => "bv",
	"brazil" => "br",
	"british indian ocean territory" => "io",
	"brunei darussalam" => "bn",
	"bulgaria" => "bg",
	"burkina faso" => "bf",
	"burundi" => "bi",
	"cambodia" => "kh",
	"cameroon" => "cm",
	"canada" => "ca",
	"cape verde" => "cv",
	"cayman islands" => "ky",
	"central african republic" => "cf",
	"chad" => "td",
	"chile" => "cl",
	"china" => "cn",
	"christmas island" => "cx",
	"cocos (keeling) islands" => "cc",
	"colombia" => "co",
	"comoros" => "km",
	"congo" => "cg",
	"democratic republic of the congo" => "cd",
	"cook islands" => "ck",
	"costa rica" => "cr",
	"cote d ivoire" => "ci",
	"croatia" => "hr",
	"cuba" => "cu",
	"curacao" => "cw",
	"cyprus" => "cy",
	"czech republic" => "cz",
	"denmark" => "dk",
	"djibouti" => "dj",
	"dominica" => "dm",
	"dominican republic" => "do",
	"ecuador" => "ec",
	"egypt" => "eg",
	"el salvador" => "sv",
	"equatorial guinea" => "gq",
	"eritrea" => "er",
	"estonia" => "ee",
	"ethiopia" => "et",
	"falkland islands (malvinas)" => "fk",
	"faroe islands" => "fo",
	"fiji" => "fj",
	"finland" => "fi",
	"france" => "fr",
	"french guiana" => "gf",
	"french polynesia" => "pf",
	"french southern territories" => "tf",
	"gabon" => "ga",
	"the gambia" => "gm",
	"georgia" => "ge",
	"germany" => "de",
	"ghana" => "gh",
	"gibraltar" => "gi",
	"greece" => "gr",
	"greenland" => "gl",
	"grenada" => "gd",
	"guadeloupe" => "gp",
	"guam" => "gu",
	"guatemala" => "gt",
	"guernsey" => "gg",
	"guinea" => "gn",
	"guinea bissau" => "gw",
	"guyana" => "gy",
	"haiti" => "ht",
	"heard island and mcdonald islands" => "hm",
	"holy see (vatican city state)" => "va",
	"honduras" => "hn",
	"hong kong" => "hk",
	"hungary" => "hu",
	"iceland" => "is",
	"india" => "in",
	"indonesia" => "id",
	"iran" => "ir",
	"iraq" => "iq",
	"ireland" => "ie",
	"isle of man" => "im",
	"israel" => "il",
	"italy" => "it",
	"jamaica" => "jm",
	"japan" => "jp",
	"jersey" => "je",
	"jordan" => "jo",
	"kazakhstan" => "kz",
	"kenya" => "ke",
	"kiribati" => "ki",
	"south korea" => "kp",
	"north korea" => "kr",
	"kuwait" => "kw",
	"kyrgyzstan" => "kg",
	"laos" => "la",
	"latvia" => "lv",
	"lebanon" => "lb",
	"lesotho" => "ls",
	"liberia" => "lr",
	"libya" => "ly",
	"liechtenstein" => "li",
	"lithuania" => "lt",
	"luxembourg" => "lu",
	"macau" => "mo",
	"macedonia (fyrom)" => "mk",
	"madagascar" => "mg",
	"malawi" => "mw",
	"malaysia" => "my",
	"maldives" => "mv",
	"mali" => "ml",
	"malta" => "mt",
	"marshall islands" => "mh",
	"martinique" => "mq",
	"mauritania" => "mr",
	"mauritius" => "mu",
	"mayotte" => "yt",
	"mexico" => "mx",
	"micronesia, federated states of" => "fm",
	"moldova, republic of" => "md",
	"monaco" => "mc",
	"mongolia" => "mn",
	"montenegro" => "me",
	"montserrat" => "ms",
	"morocco" => "ma",
	"mozambique" => "mz",
	"myanmar" => "mm",
	"namibia" => "na",
	"nauru" => "nr",
	"nepal" => "np",
	"the netherlands" => "nl",
	"new caledonia" => "nc",
	"new zealand" => "nz",
	"nicaragua" => "ni",
	"niger" => "ne",
	"nigeria" => "ng",
	"niue" => "nu",
	"norfolk island" => "nf",
	"northern mariana islands" => "mp",
	"norway" => "no",
	"oman" => "om",
	"pakistan" => "pk",
	"palau" => "pw",
	"palestinian territory, occupied" => "ps",
	"panama" => "pa",
	"papua new guinea" => "pg",
	"paraguay" => "py",
	"peru" => "pe",
	"philippines" => "ph",
	"pitcairn islands" => "pn",
	"poland" => "pl",
	"portugal" => "pt",
	"puerto rico" => "pr",
	"qatar" => "qa",
	"reunion" => "re",
	"romania" => "ro",
	"russian federation" => "ru",
	"rwanda" => "rw",
	"saint barthelemy" => "bl",
	"saint helena, ascension and tristan da cunha" => "sh",
	"st kitts and nevis" => "kn",
	"st lucia" => "lc",
	"saint martin (french part)" => "mf",
	"saint pierre and miquelon" => "pm",
	"saint vincent and the grenadines" => "vc",
	"samoa" => "ws",
	"san marino" => "sm",
	"sao tome and principe" => "st",
	"saudi arabia" => "sa",
	"senegal" => "sn",
	"serbia" => "rs",
	"seychelles" => "sc",
	"sierra leone" => "sl",
	"singapore" => "sg",
	"sint maarten (dutch part)" => "sx",
	"slovakia" => "sk",
	"slovenia" => "si",
	"solomon islands" => "sb",
	"somalia" => "so",
	"south africa" => "za",
	"south georgia and the south sandwich islands" => "gs",
	"spain" => "es",
	"sri lanka" => "lk",
	"sudan" => "sd",
	"suriname" => "sr",
	"svalbard and jan mayen" => "sj",
	"swaziland" => "sz",
	"sweden" => "se",
	"switzerland" => "ch",
	"syria" => "sy",
	"taiwan, province of china" => "tw",
	"tajikistan" => "tj",
	"tanzania" => "tz",
	"thailand" => "th",
	"timor leste" => "tl",
	"togo" => "tg",
	"tokelau" => "tk",
	"tonga" => "to",
	"trinidad and tobago" => "tt",
	"tunisia" => "tn",
	"turkey" => "tr",
	"turkmenistan" => "tm",
	"turks and caicos islands" => "tc",
	"tuvalu" => "tv",
	"uganda" => "ug",
	"ukraine" => "ua",
	"united arab emirates" => "ae",
	"united kingdom" => "gb",
	"united states" => "us",
	"united states minor outlying islands" => "um",
	"uruguay" => "uy",
	"uzbekistan" => "uz",
	"vatican city" => "va",
	"vanuatu" => "vu",
	"venezuela" => "ve",
	"vietnam" => "vn",
	"virgin islands, british" => "vg",
	"virgin islands, u.s." => "vi",
	"wallis and futuna" => "wf",
	"western sahara" => "eh",
	"yemen" => "ye",
	"zambia" => "zm",
	"zimbabwe" => "zw",
      }
    end
    if @mapping.has_key?(country)
      return @mapping[country]
    else
      return "not found"
    end
  end
end
